version: 2
registries:
  maven-repository-maven-pkg-github-com-navikt-fp-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles/
    username: x-access-token
    password: "${{secrets.MAVEN_REPOSITORY_MAVEN_PKG_GITHUB_COM_NAVIKT_FP_FELLES_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: no.nav.familie.felles:sikkerhet
    versions:
    - 1.20210323103117_8af84b9
    - 1.20210324134317_a391a3a
    - 1.20210416135502_5bf9eff
  - dependency-name: no.nav.familie.felles:http-client
    versions:
    - 1.20210323103117_8af84b9
    - 1.20210324134317_a391a3a
    - 1.20210416135502_5bf9eff
  - dependency-name: no.nav.familie.felles:log
    versions:
    - 1.20210323103117_8af84b9
    - 1.20210324134317_a391a3a
    - 1.20210416135502_5bf9eff
  - dependency-name: no.nav.security:token-validation-test-support
    versions:
    - 1.3.4
  - dependency-name: no.nav.security:token-client-spring
    versions:
    - 1.3.4
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.3
    - 2.4.4
  - dependency-name: no.nav.familie.kontrakter:felles
    versions:
    - 2.0_20210308102146_90cb778
    - 2.0_20210311094901_8f7cf3f
  - dependency-name: no.nav.familie.kontrakter:kontantstotte
    versions:
    - 2.0_20210308102146_90cb778
    - 2.0_20210311094901_8f7cf3f
  - dependency-name: org.springframework.boot:spring-boot-configuration-processor
    versions:
    - 2.4.3
  - dependency-name: org.springframework.cloud:spring-cloud-vault-config-databases
    versions:
    - 3.0.1
  - dependency-name: org.springframework.vault:spring-vault-core
    versions:
    - 2.3.1
  registries:
  - maven-repository-maven-pkg-github-com-navikt-fp-felles
