apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8083
  liveness:
    path: /internal/status/isAlive
    initialDelay: 50
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 50
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: 1000m
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ks-sak.nais.adeo.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    # Setter proxy, men dropper nav.no slik at vi kan kalle sentry (https://sentry.gc.nav.no/)
    - name: JAVA_PROXY_OPTIONS
      value: -Dhttp.proxyHost=webproxy.nais -Dhttps.proxyHost=webproxy.nais -Dhttp.proxyPort=8088 -Dhttps.proxyPort=8088 -Dhttp.nonProxyHosts=localhost|127.0.0.1|10.254.0.1|*.local|*.adeo.no|*.aetat.no|*.devillo.no|*.oera.no|*.nais.io

