apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ks-sak
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: repo.adeo.no:5443/familie-ks-sak:RELEASE_VERSION
  port: 8080
  liveness:
    path: /internal/status/isAlive
    initialDelay: 20
  readiness:
    path: /internal/status/isAlive
    initialDelay: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 200m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ks-sak.nais.adeo.no
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
