no.nav.security.oidc:
  issuers: intern
  issuer.intern:
    discoveryurl: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${GYLDIGE_SRVBRUKERE}
    cookie_name: ID_token

spring:
  datasource:
    url: jdbc:postgresql://a01dbfl039.adeo.no:5432/familie-ks-sak

# Appdynamics
APPDYNAMICS_CONTROLLER_HOST_NAME: appdynamics.adeo.no
APPDYNAMICS_CONTROLLER_PORT: 443
APPDYNAMICS_CONTROLLER_SSL_ENABLED: true
APPDYNAMICS_AGENT_ACCOUNT_NAME: PROD

FAMILIE_KS_OPPSLAG_API_URL: http://familie-ks-oppslag/api
