no.nav.security.oidc:
  issuers: intern
  issuer.intern:
    discoveryurl: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${GYLDIGE_SRVBRUKERE}
    cookie_name: ID_token

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl008.preprod.local:5432/familie-ks-sak