no.nav.security.oidc:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

credential:
  username: "srv-ks-sak"
  password: "not-a-real-password"

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql=false
    hibernate:
      ddl-auto: create
  flyway:
    enabled: false
server:
  port: 8083