no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${KS_SAK_FRONTEND_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token
  issuer.azuread_intern:
    discoveryurl: https://login.microsoftonline.com/navno.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${KS_MOTTAK_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

spring:
  datasource:
    url: jdbc:postgresql://a01dbfl039.adeo.no:5432/familie-ks-sak

# Appdynamics
APPDYNAMICS_CONTROLLER_HOST_NAME: appdynamics.adeo.no
APPDYNAMICS_CONTROLLER_PORT: 443
APPDYNAMICS_CONTROLLER_SSL_ENABLED: true
APPDYNAMICS_AGENT_ACCOUNT_NAME: PROD

FAMILIE_KS_OPPSLAG_API_URL: http://familie-ks-oppslag/api

#Unleash
UNLEASH_API_URL: https://unleash.nais.adeo.no/api/
ENVIRONMENT_NAME: p
