no.nav.security.jwt:
  issuer.intern:
    discoveryurl: https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${GYLDIGE_SRVBRUKERE}
    cookie_name: ID_token
  issuer.azuread:
    discoveryurl: https://login.microsoftonline.com/navq.onmicrosoft.com/v2.0/.well-known/openid-configuration
    accepted_audience: ${KS_SAK_FRONTEND_CLIENT_ID}
    proxyurl: http://webproxy-nais.nav.no:8088
    cookie_name: azure_token

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl008.preprod.local:5432/familie-ks-sak

FAMILIE_KS_OPPSLAG_API_URL: http://familie-ks-oppslag/api

#Unleash
UNLEASH_API_URL: https://unleash.nais.adeo.no/api/
ENVIRONMENT_NAME: q0
