ALTER TABLE SO_AKTOER_ARBEID_YTELSE_UTLAND
    DROP COLUMN AKTOER;

ALTER TABLE SO_AKTOER_TILKNYTNING_UTLAND
    DROP COLUMN AKTOER;

ALTER TABLE SO_BARN
    DROP COLUMN AKTOER_ID;

ALTER TABLE SO_SOKNAD
    ADD COLUMN SOKER_FNR VARCHAR;

ALTER TABLE SO_SOKNAD
    ADD COLUMN OPPGITT_ANNENPART_FNR VARCHAR;


