ALTER TABLE PO_PERSON
    ADD COLUMN person_ident VARCHAR(50) NOT NULL DEFAULT 'X';

ALTER TABLE PO_RELASJON
    ADD COLUMN fra_person_ident VARCHAR(50) NOT NULL DEFAULT 'X',
    ADD COLUMN til_person_ident VARCHAR(50) NOT NULL DEFAULT 'X';

