ALTER TABLE PO_PERSON
    ALTER COLUMN aktoer_id DROP NOT NULL,
    ADD COLUMN person_ident VARCHAR(50) NOT NULL DEFAULT 'X';

ALTER TABLE PO_RELASJON
    ALTER COLUMN fra_aktoer_id DROP NOT NULL,
    ALTER COLUMN til_aktoer_id DROP NOT NULL,
    ADD COLUMN fra_person_ident VARCHAR(50) NOT NULL DEFAULT 'X',
    ADD COLUMN til_person_ident VARCHAR(50) NOT NULL DEFAULT 'X';

